/*
CREATE TABLE tasks (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(300),
    done BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
*/
CREATE TABLE MAQUINARIA (
    ID_ACTIVO_M VARCHAR(15) PRIMARY KEY,
    NUM_INVENTARIO INT NOT NULL,
    ESTATUS VARCHAR(20),
    NOMBRE VARCHAR(20),
    COMPONENTES VARCHAR(200),
    CATEGORIA VARCHAR(50),
    MARCA VARCHAR(20),
    MODELO VARCHAR(30),
    NUM_SERIE INT,
    CENTRO_DE_COSTO VARCHAR(50),
    UBICACION VARCHAR(100)
);

CREATE TABLE MANTENCION (
    ID_MANTENCION INT AUTO_INCREMENT,
    TIPO_MANTENIMIENTO VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(150),
    REPUESTOS VARCHAR(50),
    MATERIALES VARCHAR(100),
    NIVEL_CRITICIDAD VARCHAR(20),
    CAUSAS_POSIBLES VARCHAR(50),
    LIMPIEZA BOOL,
    PRIMARY KEY (ID_MANTENCION)
);

CREATE TABLE HERRAMIENTA (
    ID_ACTIVO_H INT AUTO_INCREMENT,
    NUM_INVENTARIO INT NOT NULL,
    ESTATUS VARCHAR(20),
    NOMBRE VARCHAR(20),
    COMPONENTES VARCHAR(20),
    CATEGORIA VARCHAR(20),
    MARCA VARCHAR(20),
    MODELO VARCHAR(20),
    NUMSERIE INT,
    CENTRO_DE_COSTO VARCHAR(50),
    UBICACION VARCHAR(50),
    PRIMARY KEY (ID_ACTIVO_H)
);

CREATE TABLE CLIENTE (
    RUT_CLIENTE VARCHAR(12),
    NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
    DIRECCION_CLIENTE VARCHAR(50),
    TELEFONO_CLIENTE INT,
    EMPRESA_CLIENTE VARCHAR(20),
    ESTADO BOOL,
    PRIMARY KEY (RUT_CLIENTE)
);

CREATE TABLE SALA (
    NUMERO_SALA INT AUTO_INCREMENT,
    DESCRIPCION_SALA VARCHAR(100),
    TIPO_SALA VARCHAR(20) NOT NULL,
    EQUIPAMIENTO VARCHAR(20),
    PRIMARY KEY (NUMERO_SALA)
);
    
CREATE TABLE PERSONAL_MANTENCION_EXTERNA (
    ID_EMPRESA_EXTERNA VARCHAR(12),
    NOMBRE_PERSONAL_MANTENCION VARCHAR(50) NOT NULL,
    NOMBRE_EMPRESA_MANTENCION VARCHAR(50) NOT NULL,
    CARGO_PERSONAL_MANTENCION VARCHAR(20) NOT NULL,
    DIRECCION_EMPRESA_MANTENCION VARCHAR(50),
    TELEFONO_EMPRESA_MANTENCION INT,
    PRIMARY KEY (ID_EMPRESA_EXTERNA)
);

CREATE TABLE PERSONAL_LABORATORIO (
    RUT_PERSONAL_LABORATORIO VARCHAR(12),
    NOMBRE_PERSONAL_LABORATORIO VARCHAR(50) NOT NULL,
    CARGO_PERSONAL_LABORATORIO VARCHAR(20) NOT NULL,
    AREA_PERSONAL_LABORATORIO VARCHAR(20),
    DIRECCION_PERSONAL_LABORATORIO VARCHAR(50),
    TELEFONO_PERSONAL_LABORATORIO INT,
    PRIMARY KEY (RUT_PERSONAL_LABORATORIO)
);

CREATE TABLE ENCARGADO   (
    RUT_ENCARGADO VARCHAR(50),
    NOMBRE_ENCARGADO VARCHAR(20) NOT NULL,
    AREA_ENCARGADO VARCHAR(20),
    DIRECCION_ENCARGADO VARCHAR(50),
    TELEFONO_ENCARGADO INT,
    NUMERO_SALA INT,
    ID_ACTIVO_H INT,
    ID_ACTIVO_M VARCHAR(15),
    ID_MANTENCION INT,
    PRIMARY KEY (RUT_ENCARGADO),
    FOREIGN KEY (ID_ACTIVO_H) REFERENCES HERRAMIENTA(ID_ACTIVO_H),
    FOREIGN KEY (ID_ACTIVO_M) REFERENCES MAQUINARIA(ID_ACTIVO_M),
    FOREIGN KEY (ID_MANTENCION) REFERENCES MANTENCION(ID_MANTENCION)
);

CREATE TABLE TIENE (
    ID_ACTIVO_M VARCHAR(15),
    ID_MANTENCION INT AUTO_INCREMENT,
    PIEZAS_MAQUINARIA_MANTENCION VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID_ACTIVO_M, ID_MANTENCION),
    FOREIGN KEY (ID_ACTIVO_M) REFERENCES MAQUINARIA(ID_ACTIVO_M),
    FOREIGN KEY (ID_MANTENCION) REFERENCES MANTENCION(ID_MANTENCION)
);

CREATE TABLE MANEJA (
    ID_RESERVA_MAQUINARIA INT PRIMARY KEY,
    ID_ACTIVO_M VARCHAR(15),
    RUT_CLIENTE VARCHAR(12),
    FECHA_USO_MAQUINARIA DATE NOT NULL,
    HORA_LLEGADA_USO_MAQUINARIA TIME,
    DESCRIPCION_USO_MAQUINARIA VARCHAR(150) NOT NULL,
    HORA_SALIDA_USO_MAQUINARIA TIME,
    FOREIGN KEY (ID_ACTIVO_M) REFERENCES MAQUINARIA(ID_ACTIVO_M),
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE)
);
    
CREATE TABLE USA (
    NUMERO_SALA INT AUTO_INCREMENT,
    RUT_CLIENTE VARCHAR(12),
    FECHA_USO_SALA DATE NOT NULL,
    HORA_LLEGADA_USO_SALA TIME,
    DESCRIPCION_USO_SALA VARCHAR(150) NOT NULL,
    HORA_SALIDA_USO_SALA TIME,
    PRIMARY KEY (NUMERO_SALA, RUT_CLIENTE),
    FOREIGN KEY (NUMERO_SALA) REFERENCES SALA(NUMERO_SALA),
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE)
);

CREATE TABLE UTILIZA (
    RUT_CLIENTE VARCHAR(12),
    ID_ACTIVO_H INT AUTO_INCREMENT,
    FECHA_USO_HERRAMIENTA DATE NOT NULL,
    HORA_LLEGADA_HERRAMIENTA TIME,
    HORA_SALIDA_HERRAMIENTA TIME,
    DESCRIPCION_USO_HERRAMIENTA VARCHAR(150) NOT NULL,
    PRIMARY KEY (RUT_CLIENTE, ID_ACTIVO_H),
    FOREIGN KEY (RUT_CLIENTE) REFERENCES CLIENTE(RUT_CLIENTE),
    FOREIGN KEY (ID_ACTIVO_H) REFERENCES HERRAMIENTA(ID_ACTIVO_H)
);

CREATE TABLE EFECTUA (  
    ID_EMPRESA_EXTERNA VARCHAR(12),
    ID_MANTENCION INT AUTO_INCREMENT,
    HORA_INICIO_MANTENCION TIME,
    HORA_FINAL_MANTENCION TIME,
    FECHA_INICIO_MANTENCION DATE NOT NULL,
    FECHA_FINAL_MANTENCION DATE NOT NULL,
    CARACTERISTICAS_TECNICAS VARCHAR(150) NOT NULL,
    PRIMARY KEY (ID_EMPRESA_EXTERNA, ID_MANTENCION),
    FOREIGN KEY (ID_EMPRESA_EXTERNA) REFERENCES PERSONAL_MANTENCION_EXTERNA(ID_EMPRESA_EXTERNA),
    FOREIGN KEY (ID_MANTENCION) REFERENCES MANTENCION(ID_MANTENCION)
);
        
CREATE TABLE REALIZA (
    RUT_PERSONAL_LABORATORIO VARCHAR(12),
    ID_MANTENCION INT AUTO_INCREMENT,
    HORA_INICIO_MANTENCION TIME,
    HORA_FINAL_MANTENCION TIME,
    FECHA_INICIO_MANTENCION DATE NOT NULL,
    FECHA_FINAL_MANTENCION DATE NOT NULL,
    CARACTERISTICAS_TECNICAS VARCHAR(150) NOT NULL,
    PRIMARY KEY (RUT_PERSONAL_LABORATORIO, ID_MANTENCION),
    FOREIGN KEY (RUT_PERSONAL_LABORATORIO) REFERENCES PERSONAL_LABORATORIO(RUT_PERSONAL_LABORATORIO),
    FOREIGN KEY (ID_MANTENCION) REFERENCES MANTENCION(ID_MANTENCION)
);

